
steps:
- task:  NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
- script: |
    npm install -g @testim/testim-cli
    myBuildNum=$(echo $(Build.BuildNumber) | sed -e 's/^.*\(.\)$/\1/')
    echo "Build Number is : "  $myBuildNum
  displayName: 'npm install testim-cli'
- script: |
    testim \
    --token $(TestimToken) \
    --project $(TestimProject) \
    --grid "TESTIM-HA-GRID" \
    --report-file testim-tests-report.xml \
    --test-plan "AzureDevops" \
    --mode selenium \
    --report-file "testim-report.xml" \
    --parallel 5 \
    --result-label "AzureDevops Build:  $(myBuildNum)" \
    --turbo-mode
